version: "3"

services:
  scraper:
    image: nopenix/xpath-scraper
    restart: unless-stopped
    volumes: 
      - .\scraper.ps1:/app/scraper.ps1 # This is for Developing purpose! please comment this out in productive envoronments
    environment:
      SCRAPER_CYCLE_PAUSE: 1
      DB_SERVER_HOSTNAME: db
      DB_SERVER_PORT: 3306
      DB_SERVER_USERNAME: root
      DB_SERVER_PASSWORD: changemeplz
      DB_SERVER_DATABASE: scraper
      #DB_SERVER_TABLENAME_TARGETS: 
      #DB_SERVER_TABLENAME_RESULTS:  

  db:
    image: mariadb:10.3
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changemeplz
      TZ: Europe/Berlin
    volumes:
      - mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  mariadb: